### ISSUE TITLE
generalisedkummer broken

### ISSUE THREAD

**Issue by 8d1h** [pbelmans/hodge-diamond-cutter#7]
Hi!

The function for generalized Kummer is broken (due to the fact that Sage has switched to Python 3, I think).
https://github.com/pbelmans/hodge-diamond-cutter/blob/a2f2ee214c94f0e18eb823c5e747d9ac697bbb5e/diamond.sage#L954
The `gcd(a.keys())` should be changed to `gcd(list(a.keys()))`.

**Comment by pbelmans** [comment]
Thanks for noticing this, and suggesting the fix along with it!

**Comment by 8d1h** [comment]
Sure!

Also, `partial_flag_variety` does not accept `[]` as indices (the problem is with `subtype`), so there should probably be a check
https://github.com/pbelmans/hodge-diamond-cutter/blob/1dbad16141f128bb9b5977269ab81e3f932075c5/diamond.sage#L1198
```python
    if I != []:
        WL = D.subtype(I).root_system().root_lattice().weyl_group()
        Q = prod([sum([x^i for i in range(n)]) for n in WL.degrees()])
    else:
        Q = 1
```
Though strictly speaking this case isn't "partial" :)
